<?php require VIEWS_PATH . 'includes/header.phtml'?>

<main role="main" class="container">

  <div class="jumbotron">
    <h1>Usuários</h1>
    <p class="lead"> Gerenciador de Usuários </p>
    <?php require VIEWS_PATH . 'includes/messages.phtml' ?>
  </div>

</main>

<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Nome</th>
        <th>Sobrenome</th>
        <th>E-mail</th>
        <th>Username</th>
        <th>Criado em</th>
        <th>Ação</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach($this->users as $u):?>
        <tr>
          <td><?=$u['id']?></td>
          <td><?=$u['first_name']?></td>
          <td><?=$u['last_name']?></td>
          <td><?=$u['email']?></td>
          <td><?=$u['username']?></td>
          <td><?=date('d/m/Y H:i:s', strtotime($u['created_at']))?></td>
          <td>
            <a href="<?=HOME?>/user/edit/<?=$u['id']?>" class="btn btn-default"> Editar </a>
            <a href="<?=HOME?>/user/remove/<?=$u['id']?>" class="btn btn-danger"> Excluir </a>
          </td>
        </tr>
      <?php endforeach ?>
    </tbody>
  </table>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'?>
