<?php require VIEWS_PATH . 'includes/header.phtml'?>

<div class="container">

    <h1>Cadastro de Usuários</h1>
    <?php require VIEWS_PATH . 'includes/messages.phtml' ?>

    <form action="<?=HOME?>/user/new" method="post">
    <div class="form-group">
            <label for="">Nome</label>
            <input type="text" class="form-control" name="first_name">
        </div>
        <div class="form-group">
            <label for="">Sobrenome</label>
            <input type="text" class="form-control" name="last_name">
        </div>
        <div class="form-group">
            <label for="">E-mail</label>
            <input type="text" class="form-control" name="email">
        </div>
        <div class="form-group">
            <label for="">Username</label>
            <input type="text" class="form-control" name="username">
        </div>
        <div class="form-group">
            <label for="">Senha</label>
            <input type="password" class="form-control" name="password">
        </div>
        <div class="form-group">
            <label for="">Confirme a Senha</label>
            <input type="password" class="form-control" name="password_confirm">
        </div>
        <button type="submit" class="btn btn-primary">Salvar usuário</button>
    </form>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'?>