<?php require VIEWS_PATH . 'includes/header.phtml'?>

<div class="container">

    <h1>Cadastro de postagens</h1>
    <?php require VIEWS_PATH . 'includes/messages.phtml' ?>

    <form action="<?=HOME?>/blog/new" method="post">
        <div class="form-group">
            <label for="">Titulo</label>
            <input type="text" class="form-control" name="title">
        </div>
        <div class="form-group">
            <label for="">Conteúdo</label>
            <textarea class="form-control" name="content" cols="10" rows="5"></textarea>
        </div>
        <div class="form-group">
            <label for="">Categoria</label>
            <select name="category_id" class="form-control">
                <option value="">Selecione uma categoria</option>
                <?php foreach($this->categories as $c):?>
                    <option value="<?=$c['id']?>"><?=$c['name']?></option>
                <?php endforeach ?>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Salvar post</button>
    </form>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'?>